AGENTIC_COMMERCE_ABI = [
    {
        "type": "function",
        "name": "createJob",
        "stateMutability": "nonpayable",
        "inputs": [
            {"name": "provider", "type": "address"},
            {"name": "evaluator", "type": "address"},
            {"name": "expiredAt", "type": "uint256"},
            {"name": "description", "type": "string"},
            {"name": "hook", "type": "address"},
        ],
        "outputs": [{"name": "", "type": "uint256"}],
    },
    {
        "type": "function",
        "name": "setBudget",
        "stateMutability": "nonpayable",
        "inputs": [
            {"name": "jobId", "type": "uint256"},
            {"name": "amount", "type": "uint256"},
            {"name": "optParams", "type": "bytes"},
        ],
        "outputs": [],
    },
    {
        "type": "function",
        "name": "fund",
        "stateMutability": "nonpayable",
        "inputs": [
            {"name": "jobId", "type": "uint256"},
            {"name": "optParams", "type": "bytes"},
        ],
        "outputs": [],
    },
    {
        "type": "function",
        "name": "submit",
        "stateMutability": "nonpayable",
        "inputs": [
            {"name": "jobId", "type": "uint256"},
            {"name": "deliverable", "type": "bytes32"},
            {"name": "optParams", "type": "bytes"},
        ],
        "outputs": [],
    },
    {
        "type": "function",
        "name": "complete",
        "stateMutability": "nonpayable",
        "inputs": [
            {"name": "jobId", "type": "uint256"},
            {"name": "reason", "type": "bytes32"},
            {"name": "optParams", "type": "bytes"},
        ],
        "outputs": [],
    },
    {
        "type": "function",
        "name": "reject",
        "stateMutability": "nonpayable",
        "inputs": [
            {"name": "jobId", "type": "uint256"},
            {"name": "reason", "type": "bytes32"},
            {"name": "optParams", "type": "bytes"},
        ],
        "outputs": [],
    },
    {
        "type": "function",
        "name": "claimRefund",
        "stateMutability": "nonpayable",
        "inputs": [{"name": "jobId", "type": "uint256"}],
        "outputs": [],
    },
    {
        "type": "function",
        "name": "getJob",
        "stateMutability": "view",
        "inputs": [{"name": "jobId", "type": "uint256"}],
        "outputs": [
            {
                "name": "",
                "type": "tuple",
                "components": [
                    {"name": "id", "type": "uint256"},
                    {"name": "client", "type": "address"},
                    {"name": "provider", "type": "address"},
                    {"name": "evaluator", "type": "address"},
                    {"name": "description", "type": "string"},
                    {"name": "budget", "type": "uint256"},
                    {"name": "expiredAt", "type": "uint256"},
                    {"name": "status", "type": "uint8"},
                    {"name": "hook", "type": "address"},
                ],
            }
        ],
    },
    {
        "type": "function",
        "name": "jobCounter",
        "stateMutability": "view",
        "inputs": [],
        "outputs": [{"name": "", "type": "uint256"}],
    },
    {
        "type": "function",
        "name": "paymentToken",
        "stateMutability": "view",
        "inputs": [],
        "outputs": [{"name": "", "type": "address"}],
    },
    {
        "type": "event",
        "name": "JobCreated",
        "inputs": [
            {"name": "jobId", "type": "uint256", "indexed": True},
            {"name": "client", "type": "address", "indexed": True},
            {"name": "provider", "type": "address", "indexed": True},
            {"name": "evaluator", "type": "address", "indexed": False},
            {"name": "expiredAt", "type": "uint256", "indexed": False},
            {"name": "hook", "type": "address", "indexed": False},
        ],
        "anonymous": False,
    },
]
